### ISSUE TITLE
Why `class G { }` in `{ }` scope avoid `G;` treated as global?

### ISSUE THREAD

**Issue by LongTengDao** [ForbesLindesay/acorn-globals#44]
```js
{
    class G { }
}
G;
```

```js
detect(above) // []
```

Which found in [`test/fixtures/class.js`](https://github.com/ForbesLindesay/acorn-globals/blob/master/test/fixtures/class.js) and used at [`test/index.js#L40`](https://github.com/ForbesLindesay/acorn-globals/blame/master/test/index.js#L40).

In fact, `class` is equal to `const`, and it's scope is only `{ }`, the `G` outside it doesn't refer to the `class`.

---

@TimothyGu Hi, would you help to explain? Thank you! (I found you in the commit <https://github.com/ForbesLindesay/acorn-globals/commit/f46e53ce70f3325ad1a51b0d16b9f3d2809e576e#diff-d57a8e08e9a4aea760326e450e1f9911>.)

**Comment by TimothyGu** [comment]
I'm not sure. This seems like a bug to me.

**Comment by ForbesLindesay** [comment]
Right, that's exactly what this test is covering. Because the `class G { }` in your example is declared in the `{}` scope, The `G;` outside must refer to some global `G`. The test is asserting that we detect this reference to the global `G`.

Thanks for your vigilance.

**Comment by LongTengDao** [comment]
@ForbesLindesay Hi

If the `G;` outsidie refer to global `G`, then `detect()` should return `[{ name: 'G' }]`, not `[]`.

**Comment by ForbesLindesay** [comment]
Ah, my bad. You're right, https://github.com/ForbesLindesay/acorn-globals/blob/d38d49776b252e783c042699c382bdea40bff73e/index.js#L117 should be using `isBlockScope`

I think I was matching behaviour in babel when I wrote this, but it makes more sense to match the actual spec.

**Comment by LongTengDao** [comment]
@ForbesLindesay Oh, thanks for your reply! Will this be fixed in plan? I can't help to provide a PR like previous issue, because it's hard to me.

**Comment by ForbesLindesay** [comment]
It is now fixed in release 4.3.2
