### ISSUE TITLE
Seems to have broken with Acorn 1.1.0

### ISSUE THREAD

**Issue by domenic** [ForbesLindesay/acorn-globals#7]
At least, the tests are failing, and jsdom is breaking in similar ways: https://github.com/tmpvar/jsdom/issues/1131 https://github.com/marijnh/acorn/issues/263

Acorn's fault but thought I'd bring it to your attention...

**Comment by domenic** [comment]
I guess we can repurpose this bug to be "upgrade to acorn 2.0.0 compatibility" (which is obviously less urgent).

**Comment by TimothyGu** [comment]
we have upgraded to acorn 2 a long time ago now.
